### ISSUE TITLE
Writes doesn't support the Char AnyVal class.

### ISSUE THREAD

**Issue by lepirlouit** [playframework/play-json#124]
I want to implement this in class play.api.libs.json.Writes and in play.api.libs.json.Reads

**Comment by fancywriter** [comment]
What do you mean, doesn't support? Could you give some example?
```
val charFormat = new Format[Char] { def reads = ???; def writes = ??? }
```
How exactly do you want to serialize char? As far as I understand, in JSON types structure, there is no such thing as **char**, there are only strings.

**Comment by lepirlouit** [comment]
code :
 ```    val char = 'C'```
```    val jsonValue = Json.toJson(char)```

Current result : Compilation error : No Json serializer found for type Char. Try to implement an implicit Writes or Format for this type.

Expected result : serialise it as a string

**Comment by gmethvin** [comment]
@lepirlouit a serializer for `Char` is not provided by default because there are multiple ways you might wish to serialize it depending on the context. Chars can be serialized to numbers or to a one-character string. Note that a `char` does not always represent an actual character (Java strings are UTF-16 so Unicode characters may be represented as a two-`char` surrogate pair).

It's trivial to write your own `Writes` to do what you want:
```scala
implicit val charWrites: Writes[Char] = Writes(c => JsString(c.toString))
```
