### ISSUE TITLE
release for scala 2.13.0-M4

### ISSUE THREAD

**Issue by pjfanning** [playframework/play-json#167]
Many dependencies already have builds for the milestone release
One exception is https://github.com/scalamacros/paradise/issues/118

**Comment by xuwei-k** [comment]
It's time for drop Scala 2.10 if use scala-collection-compat?

https://github.com/scala/scala-collection-compat/issues/1

**Comment by SethTisue** [comment]
macro-paradise is part of the compiler as of 2.13.0-M4, so that's not a blocker here.

even if you decide not to use scala-collection-compat in this repo, dropping Scala 2.10 from the cross-build is probably still a good idea. we (the Scala team) are aiming to support 2.11/2.12/2.13 cross-building, within reason, but we're not even thinking about 2.10. some kinds of code will cross-compile with 2.10 too, but regardless, dropping it is worth considering. the ecosystem has moved on; anyone stuck on 2.10 should be able to live with being stuck on whatever play-json version they are already using, too.

**Comment by gmethvin** [comment]
I think the time has come to drop 2.10.

**Comment by xuwei-k** [comment]
https://repo1.maven.org/maven2/com/typesafe/play/play-json_2.13.0-M4/2.7.0-M1/

**Comment by marcospereira** [comment]
Closing since now we have a release for Scala 2.13.0-M4, as pointed by @xuwei-k.

**Comment by SethTisue** [comment]
https://github.com/scala/make-release-notes/commit/e7011830f2b66b6779ec2e7b0163b8b01366cc33
