### ISSUE TITLE
Feature request: validation on generated Reads

### ISSUE THREAD

**Issue by gabbah** [playframework/play-json#212]
It would be really nice if we could add validation to some fields, even on the macro generated Reads[T]. I'm not sure if that is possible. But let's say I have a big case class, and I just want want validation on one of those fields. Currently, I have to define the Reads manually, and even repeating all fields as strings, which is not DRY, and also doesn't support refactoring.
I would basically like to be able to do something like this:

`implicit val reads = Json.reads[MyCaseClass].validating(_.someField)(min(3))`
...or something similar.

Not sure if this is possible, but would be great to have!

**Comment by cchantep** [comment]
Hi,

Please rather use the [forum](https://discuss.lightbend.com/c/play/) to ask question/first discuss feature request.

BTW there are already [`Reads.filter`](https://www.playframework.com/documentation/2.6.x/api/scala/index.html#play.api.libs.json.Reads@filter(error:play.api.libs.json.JsonValidationError)(f:A=%3EBoolean):play.api.libs.json.Reads[A]) or [`JsResult.filter`](https://www.playframework.com/documentation/2.6.x/api/scala/index.html#play.api.libs.json.JsResult@filter(otherwise:play.api.libs.json.JsError)(p:A=%3EBoolean):play.api.libs.json.JsResult[A]) that can be used for such purpose.
