### ISSUE TITLE
Create a separate module for Joda time

### ISSUE THREAD

**Issue by cchantep** [playframework/play-json#31]
Considering Java8+ time API, the Joda time support can be removed from the core of Play-JSON.
In order to keep it available for project still requiring it, the existing (deprecated) code could be moved to a separate module.

**Comment by schmitch** [comment]
There is https://github.com/playframework/play-joda already?

**Comment by cchantep** [comment]
Depends what's the goal of PlayJoda : joda support for all Play modules, or only for JSON

**Comment by gpoulin** [comment]
Looking at the [Reads[DateTime]](https://github.com/playframework/play-json/blob/master/play-json/jvm/src/main/scala/play/api/libs/json/EnvReads.scala#L461) it seems to reintroduce the issue in  playframework/playframework#4844.

**Comment by marcospereira** [comment]
@cchantep play-joda has support for json and forms, which is the same we had before moving it to its own repository.

@gpoulin looks like it was not reintroduced, but either just copied from the main repository. Anyway, since play-joda now has its own repository and could evolve independently, we can release a new version fixing this. Do you want to submit a pull request?

**Comment by cchantep** [comment]
@marcospereira In whatever repo, I would prefer a play-json-joda, not to pull play-form dependency (decouple) for a non play app using play-json&joda.

**Comment by gpoulin** [comment]
@marcospereira You mean create a sub-project `play-json-joda`? I can do that. Should it be part of this project or playframework/play-joda ?

**Comment by marcospereira** [comment]
@cchantep agree. We can keep a single repository though and have sub projects there.

@gpoulin I meant to create a pull request at playframework/play-joda to fix playframework/playframework#4844. But, as suggested above by @cchantep, we can have sub projects to better isolate the dependencies. I suggest two pull requests here since these are pretty isolated changes. :-)

**Comment by schmitch** [comment]
well I think we can have `play-forms-joda` and pull the json joda stuff into a subproject in `play-json`, I think than the stuff is a little bit more in place.

**Comment by schmitch** [comment]
I'm not sure but somehow `play-json` has reintroduced joda Reads/Writes, despites that the master branch already had them removed, is there a reason for that?

**Comment by cchantep** [comment]
Backward compatibility

**Comment by gmethvin** [comment]
Okay, so it seems we should create a new subproject here for joda `play-json-joda`, and move the joda-time utilities there. Upon upgrading, users will need to add the new dependency and import the serializers.

**Comment by gmethvin** [comment]
Because the implicits are in the default scope (`Reads`/`Writes` companions), I think it's too easy to accidentally use the wrong ones if we deprecate. I think we should totally remove joda from play-json when we create the new library.

I created a play-json-joda library here since it's simpler to keep the same versioning scheme, and I want to treat Play JSON as a separate thing from Play itself.

**Comment by cchantep** [comment]
Rather than deleting, removing the implicit qualifier so no longer found in the scope from there, and so tier code calling/importing directly won't break.
