### ISSUE TITLE
JsObject NPE upon passing null literal

### ISSUE THREAD

**Issue by xaanit** [playframework/play-json#390]
I took a quick look, hopefully I didn't miss an open (or closed) issue about this!

### Play JSON Version (2.5.x / etc)
2.8.1

### API (Scala / Java / Neither / Both)
Scala

### Operating System (Ubuntu 15.10 / MacOS 10.10 / Windows 10)
Windows 10

### JDK (Oracle 1.8.0_72, OpenJDK 1.8.x, Azul Zing)
java version "1.8.0_211"
Java(TM) SE Runtime Environment (build 1.8.0_211-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.211-b12, mixed mode)

### Library Dependencies
N/A

### Expected Behavior
Passing a null literal into `Json.obj` creation should be the same as `JsNull`
```scal
scala> Json.obj("hello" -> JsNull)
res6: play.api.libs.json.JsObject = {"hello":null}
```

### Actual Behavior
```scala
scala> Json.obj("what" -> null)
java.lang.NullPointerException
```

### Reproducible Test Case
`Json.obj("Hello" -> null)`

### Additional Info
This code works:
```scala
scala> Json.obj("what" -> (null: String))
res3: play.api.libs.json.JsObject = {"what":null}
```

**Comment by renatocaval** [comment]
Thanks @xaanit for reporting this. 

It's indeed a bug and #392 should fix it (see [diff](https://github.com/playframework/play-json/pull/392/files#diff-630adad0face606a9843a98138176be2R227-R236)).

What is happening here is that `Json.obj` is defined as `def obj(fields: (String, JsValueWrapper)*): JsObject `. 

If you pass `"foo" ->  T`, you need an implicit conversion from `T` to `JsValueWrapper` which you get automatically if you have a `Writes[T]`. 

When you pass `null`, the compiler won't look for a implicit conversion for it. Because `null` has no type, it will assume that you are passing a `null:JsValueWrapper`.

We need to detect that specific case, convert it to `JsNull`.

**Comment by dwijnand** [comment]
> Because `null` has no type

`null` is of type `Null` (or, `scala.Null`).  See [SLS §6.3](https://www.scala-lang.org/files/archive/spec/2.13/06-expressions.html#the-null-value).

**Comment by renatocaval** [comment]
Correct. So, to rectify my sentence...

> When you pass `null`, the compiler won't look for an implicit conversion for it. Because it will assume that you are passing a `null:JsValueWrapper`.
