### ISSUE TITLE
Handle Exception on JsResult combinators

### ISSUE THREAD

**Issue by cchantep** [playframework/play-json#45]
e.g. `.flatMap`, `.map` ...

**Comment by gmethvin** [comment]
I think we need a different abstraction for this, maybe something like a `Try` (`JsTry`). Ideally three cases should be handled separately:
 1. Successful parsing
 2. Parsing error due to malformed input - In an HTTP based app you'd typically return a 400 and report the error to the user.
 3. Another failure, due to a bug or unexpected exception - you'd normally return a 500 here.

You can currently do this using a `Try[JsResult[T]]` but perhaps another data structure would be easier to use.

**Comment by cchantep** [comment]
`JsResult` and `Try` are already quite isomorph, so `Try[JsResult]` doesn't look fine for me.

**Comment by gmethvin** [comment]
They have some similarities but don't seem isomorphic to me. `Try` is for general-purpose error handling. `JsResult` is for structured representation of JSON parsing results. I need to handle both cases distinctly anyway.

Much of this is user code and likely to have bugs. If someone's `Reads` throws an exception, it could be because of invalid JSON, but it could also be for a number of other reasons. Trying to stuff other unexpected errors into `JsError` is definitely the wrong way to go. It would probably result in those errors getting handled improperly or ignored,

**Comment by cchantep** [comment]
I definitely don't agree. For me, any error happening in a operation resulting in a validation related type such as `JsResult` (or `Try`, `Future`, `Either`, scalaz `Disjunction`, `Task`, cats `Xor`, ...) should be represented using this type, rather than throwing up an exception (except for fatal error due to JVM requirements).

> Try is for general-purpose error handling. JsResult is for structured representation of JSON parsing results.

First is not contradictory to the second for me. `Success` and `Failure` also are structured representation of general result.

> Much of this is user code and likely to have bugs. If someone's Reads throws an exception, it could be because of invalid JSON, but it could also be for a number of other reasons. Trying to stuff other unexpected errors into JsError is definitely the wrong way to go. It would probably result in those errors getting handled improperly or ignored.

How an error, whatever would be the cause, as represented by a `JsError` if   more ignorable

**Comment by gmethvin** [comment]
I agree with you for `Try`, `Either[Throwable, _]` (or same with xor, disjunction, etc.), and for `Future` and `Task`. Those types make it pretty evident that they're abstracting around program execution in general as opposed to a particular result. They also have APIs that explicitly provide a generic exception in the error case, not a more specific type of error like `JsError` does.

To me `JsResult` is only an abstraction around a JSON validation result. I think we should try to handle any specific exceptions that we know can be easily mapped to something invalid with the input. For any other exception, we don't know if it's related to the validity of the JSON, so I would expect the exception to bubble up as usual.

For me, it's important to distinguish between truly exceptional conditions and conditions that I would be normally expected to handle. If my application is parsing JSON, I expect to have to handle situations where people have sent me invalid JSON, for example. But if an unexpected exception occurs, it may indicate an issue with my application or a bug in a library, so I would rather handle that at a higher level. So `Try[JsResult]` is fine, since I'm planning on handling those different types of errors differently.

What we could do is provide an API that returns a `Try[JsValue]` and have a specific kind of exception for JSON validation errors (as in `JsResult.toTry`).

**Comment by cchantep** [comment]
> To me JsResult is only an abstraction around a JSON validation result. I think we should try to handle any specific exceptions that we know can be easily mapped to something invalid with the input. For any other exception, we don't know if it's related to the validity of the JSON, so I would expect the exception to bubble up as usual.

Having a mechanism handling any exception (except fatal) from JSON parsing/validation as `JsError`,

- on one side make it safer and allow to have unified error handling,
- on the other side do not prevent to recover (explicitly ignore), transform in another kind of error representation (e.g. `toTry`), or if wanted to raise an exception (which should not be the default behaviour for me), reusing the original exception or a custom one (which is commin even in Java when bubbling up).

> For me, it's important to distinguish between truly exceptional conditions and conditions that I would be normally expected to handle. 

In my opinion, there is few value to try to provide such "dispatch" mechanism: the distinction is better be done on the application side, by the developer who is aware of the context.

> But if an unexpected exception occurs, it may indicate an issue with my application or a bug in a library

 Indeed, but "rather handle that at a higher level", it's even simpler and clearer to dispatch according the error cause collected as `JsError`, not having to both handle `JsError` and catch exception.
Also with the advantage for me that any unexcepted error while in some when go through the `JsError` handling which is mandatory/provided anyway.

> So `Try[JsResult]` is fine, since I'm planning on handling those different types of errors differently.

For me `Try[JsResult]` is  generally as "redondant" as `Try[Either[Throwable]]` or `Future[Try]]`. It could indeed be used for different level of error, but only by the app developer who know the appropriate semantics to do this dispatch, not by a generic mechanism for me.

> What we could do is provide an API that returns a Try[JsValue] and have a specific kind of exception for JSON validation errors

In my mind, `Try[JsValue]` would be a better replacement for currently unsafe `JsValue` such as `parse` (but there it would need deprecation to avoid API backward incompat).

For me `Try[JsValue]` cannot be used instead of `JsResult[T]`.

You might think to use `Try[T]` in such case, also with specific JSON exception to allows to dispatch it.
I agree with that, but I think that it would require more work, including what would be required to handle API backward compatibility.

**Comment by gmethvin** [comment]
> Indeed, but "rather handle that at a higher level", it's even simpler and clearer to dispatch according the error cause collected as JsError, not having to both handle JsError and catch exception.

Well, if we're talking about the `JsError` that currently exists now, it's definitely not easier for me. If an unknown exception occurs, I want the entire exception and stack trace so I can log it.

You still have to handle the unknown exception and the JSON error as separate cases. I've seen a lot of people use `JsResult` with Play, and I think it's pretty well understood that `JsError` is only for JSON validation related errors. Normally these errors are mapped to a 400 error displayed to the user. So it's actually convenient for some people that unknown exceptions are just thrown, since they likely wouldn't know how to handle them at the call site anyway, assuming they have well-written Scala code that doesn't throw exceptions except for truly unexpected error conditions.

> Also with the advantage for me that any unexcepted error while in some when go through the JsError handling which is mandatory/provided anyway.

I'm not sure what you mean.

> For me Try[JsResult] is generally as "redondant" as Try[Either[Throwable]] or Future[Try]]. It could indeed be used for different level of error, but only by the app developer who know the appropriate semantics to do this dispatch, not by a generic mechanism for me.

I view `JsResult` similarly to `Option` or any other kind of standard algebraic data type. It's there to make sure I properly handle all possible types of result. But exceptions should be outside of that context, because when used properly they should only be thrown when there is no other known way to handle the error. Of course when exceptions are thrown as part of the API in Java APIs (`DateTimeParseException`, `NumberFormatException`, etc.), then it's appropriate to catch them and convert to whatever represents an error in my algebraic data type. But since it's idiomatic in Scala only to use exceptions for unrecoverable errors, I want a data structure that separates the exceptions from other kinds of errors I actually am supposed to handle.

There are many cases I've found multiple levels of error handling useful. The `BodyParser` API in Play is `RequestHeader => Accumulator[ByteString, Either[Result, A]]`. In this case we have `Accumulator`, which can contain generic exceptions, that is materialized to an `Either[Result, A]`. The `Either` is either a direct `Result` sent to the user if the parsing failed, or a parsed value of type `A`. There are two levels of error handling, for "expected" and "unexpected" errors. If the `Accumulator` is a failure, that indicates a serious unexpected exception, which is usually not something the body parser is interested in handling anyway.

> You might think to use Try[T] in such case, also with specific JSON exception to allows to dispatch it.
I agree with that, but I think that it would require more work, including what would be required to handle API backward compatibility.

More work than what? I'd suggest just providing alternative versions of `Json.parse`, `Json.fromJson` etc. that return `Try`. The underlying APIs like the `Reads` and `Writes` don't need to change.

**Comment by cchantep** [comment]
> *Indeed, but "rather handle that at a higher level", it's even simpler and clearer to dispatch according the error cause collected as JsError, not having to both handle JsError and catch exception.*

> Well, if we're talking about the JsError that currently exists now, it's definitely not easier for me. If an unknown exception occurs, I want the entire exception and stack trace so I can log it.

Considering the current `JsResult`, I doubt being able to represent the cause `Exception` would be that complicated (for me the `JsonValidationError` is already more complex than that).

> You still have to handle the unknown exception and the JSON error as separate cases. I've seen a lot of people use JsResult with Play, and I think it's pretty well understood that JsError is only for JSON validation related errors.

Right, but it depends on what you put behind "JSON validation related errors".

> Normally these errors are mapped to a 400 error displayed to the user.

In a web context, but even I agree it's the most frequent usage of Play JSON, I think the goal of having it as standalone is to be able to use it in any context (indeed I personally use it in this way for personal and enterprise projects).

> So it's actually convenient for some people that unknown exceptions are just thrown, since they likely wouldn't know how to handle them at the call site anyway, 

Having a `JsResult` the error handling concern is there anyway. If you think of bad code where there is `JsResult.get` no mechanism would make it better. For code where `JsResult` is already properly handle, then the error handling will already work, in a unified way, with the possibility for the app code this dispatch according the context.

> assuming they have well-written Scala code that doesn't throw exceptions except for truly unexpected error conditions.

I don't think in this way. Play JSON should for me behave well without assuming the call site will handle exception thrown aside from the explicit return type.

> It's there to make sure I properly handle all possible types of result. But exceptions should be outside of that context, because when used properly they should only be thrown when the error is not obviously recoverable.

I would rather say that a function with a return type representing error case, should *never* throw an exception other than one fatal (as `Try`).

> There are many cases I've found multiple levels of error handling useful. The BodyParser API in Play is RequestHeader => Accumulator[ByteString, Either[Result, A]]. In this case we have Accumulator, which can contain generic exceptions, that is materialized to an Either[Result, A]. 

Indeed, and it's also frequent to see `Future[Either]` or `Future[Option]` or similar monadic stacking (for which `EitherT` & co. were introduced in lib such as scalaz).

It's more an illustration of representing errors levels at type level, rather than having some errors represented in types and others thrown away as exceptions, from the same function.

> More work than what? I'd suggest just providing alternative versions of Json.parse, Json.fromJson etc. that return Try.

For `parse` it's easy to provide an alternative returning a `Try[JsValue]`.
In my mind that's not more complex to have a `JsResult` for that, with advantage of being more directly usage to chain with JSON ops.

About `fromJson`, I guess the alternative would return something like `Try[JsResult[T]]`.
Which for is unnecessary error "leveling", and overcomplicated API: any non fatal exception while parsing JSON is a JSON related error, even if the cause details allow the developer to implement a finer dispatch according the context.

> The underlying APIs like the Reads and Writes don't need to change.

On my side I don't suggest to change these types, and even about `JsResult` changes could be applied without breaking API compat.

**Comment by gmethvin** [comment]
> Considering the current `JsResult`, I doubt being able to represent the cause `Exception` would be that complicated (for me the JsonValidationError is already more complex than that).

Yeah, you could, but it would require a refactor on the users' part to make sure the exception is handled properly. And if they're going to chain a bunch of potentially exception-throwing actions together, it probably makes more sense to use a more generic type like a `Try` or a `Future`, doesn't it?

I also realized that usually when I have a `JsResult`, I'm eventually producing something inside a `Future` (e.g. `Future[Result]` in Play), so if `JsResult` handled exceptions in the same way `Future` does, I'd still end up having two levels of exception handling.

> Having a JsResult the error handling concern is there anyway. If you think of bad code where there is JsResult.get no mechanism would make it better. For code where JsResult is already properly handle, then the error handling will already work, in a unified way, with the possibility for the app code this dispatch according the context.

That's not true at all, and this part is essential to my point. Right now you can assume the errors you're handling are related to a validation failure, which you would handle in an entirely different way than an arbitrary exception.

And what about `JsResult.toOpt`? To me that's actually somewhat okay now, because you can assume a `JsError` is due to a validation error. If you don't care about providing a detailed error to the user, you can handle the `None` case in some generic way. But if it's possible some other serious exception occurred, and that exception would be ignored if in the "new" API.

> On my side I don't suggest to change these types, and even about JsResult changes could be applied without breaking API compat.

But the API is doing something different than before, and would require users to change their code. It would definitely require changes for most people using the library with Play. In most of our code and Play code I've seen, like the [JSON body parser](https://github.com/playframework/playframework/blob/master/framework/src/play/src/main/scala/play/api/mvc/BodyParsers.scala#L567), it's safe to assume `JsError` should map to a 400 error. If we can have an arbitrary exception, we'd need to add an extra case to handle that and do whatever's necessary to handle the error (usually send a 500 error).

**Comment by cchantep** [comment]
> Yeah, you could, but it would require a refactor on the users' part to make sure the exception is handled properly.

It may need refactoring for a code handling exception "around" a function producing `JsResult`.

If a unified error handling mechanism for JSON related function is considered as an improvement,  then the way to implement it regarding compat could be designed.

This change should minimal, and as long as a orginal cause is kept, any existing exception handling would be easy to merge with `JsError` handling.

> if they're going to chain a bunch of potentially exception-throwing actions together, it probably makes more sense to use a more generic type like a Try or a Future, doesn't it?

`JsError` represents semantic specific to JSON validation (such as paths), which is useful whatever is the cause/exception.

Chaining it with other validation types is for me already common, and not an issue (as with `toTry`). That's similar when `Future`/`Try` are used togather (or with similar types like scalaz or monix tasks).

> I also realized that usually when I have a JsResult, I'm eventually producing something inside a Future (e.g. Future[Result] in Play), so if JsResult handled exceptions in the same way Future does, I'd still end up having two levels of exception handling.

My concern is not about stacking error levels, but that in any case provided functions that return `JsResult` (parsing and combinators) do not throw non fatal exception.

Btw, considering stacked error representation/handling, on my mind letting exception bubbling up implicitly/by default tends more to clutter the level distinction than having an unified JSON error handling.

```scala
val res: Future[JsResult[MyT]] = for {
  raw <- someAsyncDBquery()
  v = Json.validate[MyT](raw) // Reads w/ non fatal exception
  _ <- otherFuture
} yield v
// v error stay at JSON level, not mix "up" by default

// but if dev want...
res.flatMap { jr => Future.fromTry(Json.toTry(jr)) }
```

> That's not true at all, and this part is essential to my point. Right now you can assume the errors you're handling are related to a validation failure, which you would handle in an entirely different way than an arbitrary exception.

How a non fatal exception occuring during a JSON parsing or any subsequent combination could be considered as unrelated to JSON validation/result?

> And what about JsResult.toOpt? To me that's actually somewhat okay now, because you can assume a JsError is due to a validation error. If you don't care about providing a detailed error to the user, you can handle the None case in some generic way. But if it's possible some other serious exception occurred, that exception would be ignored if in the new API containing the arbitrary exception.

Why a code to ignore any `JsError` would handle JSON exception?

> But the API is doing something different than before, and would require users to change their code. It would definitely require changes for most people using the library with Play. In most of our code and Play code I've seen, like the JSON body parser, it's safe to assume JsError should map to a 400 error. If we can have an arbitrary exception, we'd need to add an extra case to handle that and do whatever's necessary to handle the error (usually send a 500 error).

Which kind of error happening during JSON validation would better be 500? Which non fatal exception occurring while parsing JSON should not be considered related?

I understand could have impacts, but if that's to improve the lib it should be considered in my opinion.

**Comment by gmethvin** [comment]
> If a unified error handling mechanism for JSON related function is considered as an improvement, then the way to implement it regarding compat could be designed.

I don't consider it an improvement for Play users, because it actually makes it more complex to properly handle errors. The way it is now, if we throw an exception inside an `Action` block, it will result in a failed future, which is eventually reported via `HttpErrorHandler.onServerError`. If `JsResult` catches arbitrary exceptions, you'll probably still want to report that error. So the user either needs to explicitly call the `HttpErrorHandler`, return a failed future explicitly, or rethrow the exception. All of those result in less elegant code.

I really only see the benefit for users who've specifically chosen they want to handle all their exceptions through `Try` and similar abstractions.

> JsError represents semantic specific to JSON validation (such as paths), which is useful whatever is the cause/exception.

It might be useful for some exceptions, but we'd only have the path info if we have some way to catch the exception at the exact path where it occurred.

> Chaining it with other validation types is for me already common, and not an issue (as with toTry). That's similar when Future/Try are used togather (or with similar types like scalaz or monix tasks).

Then I think we should just recommend using `Try` and similar types directly.

> My concern is not about stacking error levels, but that in any case provided functions that return JsResult (parsing and combinators) do not throw non fatal exception.

I think we have a slightly different philosophy. My philosophy is to only throw *unrecoverable* exceptions, meaning that my code cannot reasonably be expected to handle it. This includes a lot of non-fatal exceptions like `IllegalStateException`, `IllegalArgumentException`, `NullPointerException`, etc. These exceptions are not fatal to the JVM, but they're usually fatal in the context of the current task. If I got a `NullPointerException` while handling an HTTP request, I would usually want to report that error and stop handling the request.

> How a non fatal exception occuring during a JSON parsing or any subsequent combination could be considered as unrelated to JSON validation/result?

Many of the exceptions mentioned above occur because of a bug in code or maybe an underlying issue with a data structure or something else in the system. In the real world, I've seen very few exceptions coming from Play JSON when used properly, but I think the last time I saw one was a `NoSuchMethodError` due to a binary compatibility issue. This obviously has nothing to do with whether the validation succeeded.

> Why a code to ignore any JsError would handle JSON exception?

If we catch and include  in the `JsError` unrecoverable exceptions, then `.toOpt` would be ignoring them. So we end up inadvertently hiding problems in our application. As it is now, we know it's only a validation error, so it's relatively safe to ignore it if we are not interested in giving detailed feedback to the user.

> Which kind of error happening during JSON validation would better be 500? Which non fatal exception occurring while parsing JSON should not be considered related?

Most `RuntimeException`s, including the ones mentioned above, would normally be a 500 error.

I would not want to report an unrecoverable exception as a validation error. Firstly, because I don't know if it's a problem in the input or a problem with my application. Secondly, because in order to report a generic exception to a user, I would probably reveal private information about my app. So it's essential to me that unrecoverable and recoverable errors are handled separately.

I'm interested to see an example of code you think would be improved, including any actual error handling.

**Comment by cchantep** [comment]
Hi,

As mentioned that's a really "different philosophy".

- `JsResult` is a validation type.
- Any function (including combinators) returning a validation type, simple (e.g. `Try[T]`) or stacked (`EitherT[Future, Throwable, T]`) should *never* throw a non fatal exception, that's to say should make sure all errors are represented using the type level.
- The distinction between the different (expected or not) causes of the errors can be done, with no extra complexity, using the different cases of the validation type.
- If needed the distinction between different kind of error level can be done, with no extra complexity, stacking validation type.
- In any case, throwing `Exception` is somewhat defeating the Least Surprise Principle and Referntial Transparency.
- The fact that tier libraries/applications are compensating mixed error representation by both considering returned validation types and catching exception is a compatibility concern, but not a blocker.

It's very unlikely such philosophy differences can be reconciled, so there is no point in keeping this open.

Best regards

**Comment by gmethvin** [comment]
I think this could be done as a different type, which we could call `JsTry`. It would essentially be a `Try[JsResult]` without the multiple levels of nesting.

Scala users in general shouldn't be throwing exceptions as part of the API, so I don't think unknown exceptions are as big of a concern as you think. When exceptions are used, they should be used for unrecoverable errors. I believe it's a matter of preference whether those errors should be represented in the type system, with the vast majority of Scala code I've seen choosing to allow those kinds of exceptions to be thrown, at least until they reach some higher-level error handling type like a `Future`.

**Comment by lforite** [comment]
As an extensive play-json user, I just want to add my bit here: I think that adding a type on top of `JsResult` would make the code more cluttered.

I would rather have the library throwing an exception, which will anyway be caught at higher level. Overall, I agree that throwing exceptions is ugly and should never be done but the ultimate question is: what can a user do more with a `Failure` than he can do with an `Exception` ? Fail gracefully ? Maybe. But from my personal experience, in this situation, you are just unable to provide the expected service.

I think that many libraries adopted this philosophy, the first example I have in mind is Slick. I also believe that it's really hard to be 100% typesafe, and we should not sacrifice usability just for the sake of being 100% typesafe.

As @cchantep mentioned it several times, there are different approaches to the problem. As for now, I am quite satisfied with the current state of the library.

**Comment by cchantep** [comment]
There is a misunderstanding, I mentioned that there are approached more safe than mixing validation types and `Exception`s as now, w/o cluttering the code. If you want, the mailing is available, even if this issue is closed.

**Comment by gmethvin** [comment]
@lforite I agree with you. I feel the current `JsResult` type is enough. I don't think Scala code in general should be using exceptions for "normal" situations; they are really meant for truly exceptional cases, which often indicate a bug in your code or something wrong with the underlying system.

Not sure if additional discussion is warranted here but if you have specific concerns we can discuss on the Play mailing list.
