### ISSUE TITLE
Scala 3 crossbuilds

### ISSUE THREAD

**Issue by rossabaker** [playframework/play-json#539]
Are there plans to crossbuild play-json for Dotty?  I'm lining up http4s dependencies, and would love to continue to support play-json in our dotty releases.

Thanks!

**Comment by ignasi35** [comment]
Hi @rossabaker, at the moment, it's not at the top of our list to support Dotty.

It'd be great if there was some community contribution in this effort. 

There'll be a few challenges because of macros. We generally try to limit the amount of code that's specific to the scala version but, because of play-json macros, we may need to relax that requirement a bit.

**Comment by SethTisue** [comment]
> @dwijnand dwijnand self-assigned this yesterday

🎉

**Comment by jtjeferreira** [comment]
Hi @dwijnand, did you noticed I created a PR for this right? Just in case we are not duplicating efforts...

**Comment by dwijnand** [comment]
Yeah I noticed you'd opened that pull request, sadly it looks like we did duplicate efforts by 1 day. 😞

**Comment by dwijnand** [comment]
Available as https://github.com/playframework/play-json/releases/tag/2.10.0-RC1 btw.

**Comment by SethTisue** [comment]
and now available for 3.0.0-RC1 as well (2.10.0-RC2)
